### ISSUE TITLE
Assistance

### ISSUE THREAD

**Issue by rolfiee** [NinjaCheetah/NCX-Core#1]
I can't get NCX-Core 3.0 working. Whenever i launch 3.0 [This](https://drive.google.com/file/d/1znWvF0S2NMbA-5okueYBFuqrqWQ6LEQX/view?usp=sharing) happens

**Comment by NinjaCheetah** [comment]
Please don't use issues to try and be funny.

**Comment by rolfiee** [comment]
Not being funny, I attempted to compile 3.0 and it didn't work, but okay.

**Comment by NinjaCheetah** [comment]
Mind telling me how you compiled it?

**Comment by rolfiee** [comment]
https://docs.microsoft.com/en-us/troubleshoot/dotnet/csharp/compile-code-using-compiler

**Comment by NinjaCheetah** [comment]
You do realize that is for compiling a C# program from within a C# program?

**Comment by rolfiee** [comment]
Yes, I do.

**Comment by NinjaCheetah** [comment]
Most people compile using a more conventional method such as `dotnet build`

**Comment by rolfiee** [comment]
I've always used the method linked above.
